"use client";
import {useEffect,useState} from "react";
export default function GuidedLeadSheet({phone,name,onClose,draftId}:{phone:string;name:string;onClose:()=>void;draftId?:string}){
 const key="lead-sheet:"+(draftId||phone||"manual");
 const [data,setData]=useState<Record<string,any>>({phone,name});
 useEffect(()=>{try{setData(prev=>({...prev,...JSON.parse(localStorage.getItem(key)||"{}")}));}catch{}},[key]);
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(data));}catch{}},[data,key]);
 const set=(k:string,v:any)=>setData(d=>({...d,[k]:v}));
 const input=(label:string,k:string,type="text")=><label style={{display:"block",margin:"10px 0"}}>{label}<input type={type} value={data[k]||""} onChange={e=>set(k,e.target.value)} style={{display:"block",width:"95%",padding:8}}/></label>;
 const check=(label:string,k:string)=><label style={{display:"inline-flex",gap:6,margin:8}}><input type="checkbox" checked={!!data[k]} onChange={e=>set(k,e.target.checked)}/>{label}</label>;
 return <div role="dialog" aria-label="Guided lead sheet" style={{position:"fixed",inset:0,zIndex:12000,background:"#0007",display:"flex",justifyContent:"flex-end"}}><section style={{background:"white",color:"#222",width:"min(600px,100vw)",height:"100%",overflow:"auto",padding:25}}><button onClick={onClose}>Close</button><h2>Guided Lead Sheet</h2><small>Draft autosaves locally. CRM save not connected.</small>{input("Caller name","name")}{input("Phone","phone")}{check("Confirmed caller name","confirmed")}<h3>Discovery</h3>{check("Tour prospect","tour")}{check("Rental prospect","rental")}{input("Travel from","arrival","date")}{input("Travel to","departure","date")}<label>Activity<select value={data.activity||""} onChange={e=>set("activity",e.target.value)}>{["","Gateway to Hell’s Revenge","Hell’s Revenge","Poison Spider Mesa","The Works","Moab Discovery","Pro R Ultimate","Private Pro Xperience","RZR Rental","Xpedition Rental","Undecided"].map(x=><option key={x}>{x}</option>)}</select></label>{input("Party size","party")}{input("What matters to the guest?","interests")}<p><a href="/quote" target="_blank">Open Quote Builder</a></p><h3>Objections</h3>{["Price / value","Activity choice","Safety / difficulty","Dates / timing","Group deciding","Researching","Comparing companies","Other"].map(x=><div key={x}>{check(x,"objection:"+x)}</div>)}{input("Notes","notes")}<h3>Actions taken</h3>{["Quote sent","Information sent","Follow-up scheduled","Guest will call back"].map(x=><div key={x}>{check(x,"action:"+x)}</div>)}<label>Primary disposition<select value={data.disposition||""} onChange={e=>set("disposition",e.target.value)}>{["","Booked","Quote / information","Follow-up needed","Researching","Lost","Not a sales lead"].map(x=><option key={x}>{x}</option>)}</select></label>{input("Next action","next")}{input("Follow-up date","followup","date")}<p>All fields optional. Draft saved on this device only.</p></section></div>;
}
