"use client";
import {useEffect,useState} from "react";
export default function GuidedLeadSheet({phone,name,onClose,draftId}:{phone:string;name:string;onClose:()=>void;draftId?:string}){
 const key="lead-sheet:"+(draftId||phone||"manual");
 const [serverId,setServerId]=useState<string|null>(null);
 const [saveStatus,setSaveStatus]=useState("Preparing C360 draft");
 const [loaded,setLoaded]=useState(false);
 const [data,setData]=useState<Record<string,any>>({phone,name});
 useEffect(()=>{try{setData(prev=>({...prev,...JSON.parse(localStorage.getItem(key)||"{}")}));}catch{}setLoaded(true);},[key]);
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(data));}catch{}},[data,key]);
 useEffect(()=>{if(!loaded)return;const timer=setTimeout(async()=>{setSaveStatus("Saving to C360...");try{const res=await fetch("/api/lead-sheets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:serverId,fields:data})});const result=await res.json();if(!res.ok||!result.rows?.[0]?.id)throw Error();setServerId(result.rows[0].id);setSaveStatus("Saved to C360");}catch{setSaveStatus("C360 save unavailable - draft remains on this device");}},1200);return()=>clearTimeout(timer);},[data,loaded,serverId]);
 const set=(k:string,v:any)=>setData(d=>({...d,[k]:v}));
 const input=(label:string,k:string,type="text")=><label style={{display:"block",margin:"10px 0"}}>{label}<input type={type} value={data[k]||""} onChange={e=>set(k,e.target.value)} style={{display:"block",width:"95%",padding:8}}/></label>;
 const check=(label:string,k:string)=><label style={{display:"inline-flex",gap:6,margin:8}}><input type="checkbox" checked={!!data[k]} onChange={e=>set(k,e.target.checked)}/>{label}</label>;
 return <div role="dialog" aria-label="Guided lead sheet" style={{position:"fixed",inset:0,zIndex:12000,background:"#0007",display:"flex",justifyContent:"flex-end"}}><section style={{background:"white",color:"#222",width:"min(600px,100vw)",height:"100%",overflow:"auto",padding:25}}><button onClick={onClose}>Close</button><h2>Guided Lead Sheet</h2><small>{saveStatus}</small>{input("Name","name")}{input("Phone","phone")}{check("Confirmed name","confirmed")}<h3>Discovery</h3>{check("Tour prospect","tour")}{check("Rental prospect","rental")}{input("Travel from","arrival","date")}{input("Travel to","departure","date")}<label>Activity<select value={data.activity||""} onChange={e=>set("activity",e.target.value)}>{["","Gateway to Hell’s Revenge","Hell’s Revenge","Poison Spider Mesa","Moab Discovery","Pro R Ultimate","Private Pro Xperience","Private Tours","RZR Rental","Undecided"].map(x=><option key={x}>{x}</option>)}</select></label>{input("Party size","party")}<h4>What matters to the guest?</h4><small>Ask what would make this experience memorable. Select all that apply.</small>{["Scenery / sightseeing","Excitement / adrenaline","Driving themselves","Comfort / enclosed vehicle","Family-friendly experience","First-time off-roading","Technical trails / challenge","Flexible schedule / independence","Budget / value","Other"].map(x=><div key={x}>{check(x,"wants:"+x)}</div>)}{input("Other priorities / helpful details","interests")}<p><a href="/quote" target="_blank">Open Quote Builder</a></p><h3>Objections</h3>{["Price / value","Activity choice","Safety / difficulty","Dates / timing","Group deciding","Researching","Comparing companies","Other"].map(x=><div key={x}>{check(x,"objection:"+x)}</div>)}{input("Notes","notes")}<h3>Actions taken</h3>{["Quote sent","Information sent","Follow-up scheduled","Guest will call back"].map(x=><div key={x}>{check(x,"action:"+x)}</div>)}<label>Primary disposition<select value={data.disposition||""} onChange={e=>set("disposition",e.target.value)}>{["","Booked","Quote / information","Follow-up needed","Researching","Lost","Not a sales lead"].map(x=><option key={x}>{x}</option>)}</select></label>{input("Next action","next")}{input("Follow-up date","followup","date")}<p>All fields optional. {saveStatus}</p></section></div>;
}
