"use client";

import { useEffect, useMemo, useState } from "react";
import Customer360Modal from "../customer-360/Customer360Modal";
import styles from "./Inbox.module.css";

type InboxThread = {
  thread_key:string; kind:string; source_id:string; occurred_at:string; preview:string|null; subject:string|null;
  customer_name:string|null; email:string|null; phone:string|null; opportunity_id:string|null; opportunity_status:string|null;
  lead_value_cents:number|null; interest_label:string|null; activity_window_start:string|null; activity_window_end:string|null;
  assigned_rep_name:string|null; claimed_by_name:string|null; reservation_id:string|null; reservation_confirmation:string|null;
  lane:"sales"|"service"|"unmatched"; is_open:boolean; handled_at:string|null; handled_by_name:string|null;
};
type InboxNote={id:string;thread_key:string;note_text:string;author_name:string|null;created_at:string|null};
type Filter="open"|"sales"|"service"|"unmatched"|"closed";
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});

function fmtTime(v:string|null){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"});}
function fmtDate(v:string|null){if(!v)return"—";const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?v:d.toLocaleDateString(undefined,{month:"short",day:"numeric"});}
function kindLabel(kind:string){if(kind==="email")return"Email";if(kind==="text")return"Text";if(kind==="abandoned_call")return"Abandoned call";if(kind==="missed_call")return"Missed call";if(kind==="voicemail")return"Voicemail";if(kind==="shopping")return"TripWorks Draft";return"Call";}
function currentStateLabel(t:InboxThread){if(t.opportunity_status==="booked")return"🎉 BOOKED";if(t.lane==="sales")return"OPEN LEAD";if(t.lane==="service")return"SERVICE";return"UNMATCHED";}
function currentStateClass(t:InboxThread){if(t.opportunity_status==="booked")return styles.booked;if(t.lane==="sales")return styles.sales;if(t.lane==="service")return styles.service;return styles.unmatched;}

export default function InboxClient(){
  const[threads,setThreads]=useState<InboxThread[]>([]);const[selectedKey,setSelectedKey]=useState<string|null>(null);const[filter,setFilter]=useState<Filter>("open");const[query,setQuery]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[customer360Open,setCustomer360Open]=useState(false);const[notes,setNotes]=useState<InboxNote[]>([]);const[noteText,setNoteText]=useState("");
  async function load(nextFilter=filter){try{const r=await fetch(`/api/inbox${nextFilter==="closed"?"?closed=1":""}`,{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error(p?.error||"Unable to load inbox.");setThreads(p.threads||[]);}catch(e){setError(e instanceof Error?e.message:"Unable to load inbox.");}}
  async function loadNotes(threadKey:string){try{const r=await fetch(`/api/inbox?thread_key=${encodeURIComponent(threadKey)}`,{cache:"no-store"});const p=await r.json();if(r.ok)setNotes(p.notes||[]);}catch{}}
  useEffect(()=>{void load(filter);const timer=window.setInterval(()=>{if(document.visibilityState==="visible")void load(filter);},5000);return()=>window.clearInterval(timer);},[filter]);
  useEffect(()=>{if(selectedKey){void loadNotes(selectedKey);setNoteText("");}else setNotes([]);},[selectedKey]);
  const visible=useMemo(()=>{const q=query.trim().toLowerCase();return threads.filter(t=>{if(filter!=="open"&&filter!=="closed"&&t.lane!==filter)return false;if(filter==="closed"&&t.is_open)return false;if(filter==="open"&&!t.is_open)return false;if(!q)return true;return[t.customer_name,t.email,t.phone,t.subject,t.preview,t.reservation_confirmation,t.interest_label].filter(Boolean).some(v=>String(v).toLowerCase().includes(q));});},[threads,filter,query]);
  const selected=useMemo(()=>visible.find(t=>t.thread_key===selectedKey)||threads.find(t=>t.thread_key===selectedKey)||null,[visible,threads,selectedKey]);
  async function closeThread(){if(!selected)return;setBusy(true);setError("");try{const r=await fetch("/api/inbox",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"close",thread_key:selected.thread_key})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error||"Unable to close conversation.");setSelectedKey(null);await load(filter);}catch(e){setError(e instanceof Error?e.message:"Unable to close conversation.");}finally{setBusy(false);}}
  async function addNote(){if(!selected||!noteText.trim())return;setBusy(true);setError("");try{const r=await fetch("/api/inbox",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"note",thread_key:selected.thread_key,note_text:noteText.trim()})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error||"Unable to add note.");setNoteText("");await loadNotes(selected.thread_key);}catch(e){setError(e instanceof Error?e.message:"Unable to add note.");}finally{setBusy(false);}}
  async function activateLead(){if(!selected?.opportunity_id)return;setBusy(true);setError("");try{const r=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"activate",opportunity_id:selected.opportunity_id})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error||"Unable to activate lead.");await load(filter);}catch(e){setError(e instanceof Error?e.message:"Unable to activate lead.");}finally{setBusy(false);}}
  const counts=useMemo(()=>({open:threads.filter(t=>t.is_open).length,sales:threads.filter(t=>t.is_open&&t.lane==="sales").length,service:threads.filter(t=>t.is_open&&t.lane==="service").length,unmatched:threads.filter(t=>t.is_open&&t.lane==="unmatched").length}),[threads]);
  return <>
    <header className={styles.header}><div><div className={styles.eyebrow}>Epic Communications</div><h1>Inbox <span className={styles.count}>{counts.open}</span></h1><p>Everything inbound stays here until somebody closes it. New customer activity brings a closed conversation back.</p></div><div className={styles.filters}><button className={`${styles.filter} ${filter==="open"?styles.filterActive:""}`} onClick={()=>setFilter("open")}>Open {counts.open}</button><button className={`${styles.filter} ${filter==="sales"?styles.filterActive:""}`} onClick={()=>setFilter("sales")}>Sales {counts.sales}</button><button className={`${styles.filter} ${filter==="service"?styles.filterActive:""}`} onClick={()=>setFilter("service")}>Service {counts.service}</button><button className={`${styles.filter} ${filter==="unmatched"?styles.filterActive:""}`} onClick={()=>setFilter("unmatched")}>Unmatched {counts.unmatched}</button><button className={`${styles.filter} ${filter==="closed"?styles.filterActive:""}`} onClick={()=>setFilter("closed")}>Closed</button></div></header>
    <div className={styles.workspace}>
      <section className={styles.listPane}><div className={styles.listHeader}><input className={styles.search} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search customer, email, phone, subject…"/></div>{error?<div className={styles.error}>{error}</div>:null}{visible.map(t=><button key={t.thread_key} className={`${styles.thread} ${selectedKey===t.thread_key?styles.selected:""}`} onClick={()=>setSelectedKey(t.thread_key)}><div className={styles.threadTop}><div className={styles.name}>{t.customer_name||t.email||t.phone||"Unknown customer"}</div><div className={styles.time}>{fmtTime(t.occurred_at)}</div></div><div className={styles.threadMeta}><span className={`${styles.pill} ${currentStateClass(t)}`}>{currentStateLabel(t)}</span><span className={`${styles.pill} ${t.kind==="shopping"?styles.tripworksDraft:""}`}>{kindLabel(t.kind)}</span></div><div className={styles.preview}>{t.subject?`${t.subject} — `:""}{t.preview||"No preview"}</div></button>)}</section>
      <section className={styles.detailPane}>{selected?<div className={styles.card}><div className={styles.detailTop}><div><div className={styles.eyebrow}>{selected.lane==="sales"?"Sales opportunity":selected.lane==="service"?"Existing customer":"Needs identification"}</div><h2>{selected.customer_name||selected.email||selected.phone||"Unknown customer"}</h2><div className={styles.sub}>{[selected.email,selected.phone].filter(Boolean).join(" · ")||"No known contact record yet"}</div></div><span className={`${styles.pill} ${currentStateClass(selected)}`}>{currentStateLabel(selected)}</span></div>
        <div className={styles.contextGrid}><div className={styles.context}><span>Latest inbound</span><strong>{kindLabel(selected.kind)}</strong></div><div className={styles.context}><span>Lead value</span><strong>{selected.lead_value_cents!=null?money.format(selected.lead_value_cents/100):"—"}</strong></div><div className={styles.context}><span>Owner</span><strong>{selected.claimed_by_name||selected.assigned_rep_name||"Unassigned"}</strong></div><div className={styles.context}><span>Interest</span><strong>{selected.interest_label||"—"}</strong></div><div className={styles.context}><span>Visit window</span><strong>{selected.activity_window_start?`${fmtDate(selected.activity_window_start)}${selected.activity_window_end&&selected.activity_window_end!==selected.activity_window_start?` – ${fmtDate(selected.activity_window_end)}`:""}`:"—"}</strong></div><div className={styles.context}><span>Reservation</span><strong>{selected.reservation_confirmation||"—"}</strong></div></div>
        <div className={styles.message}><div className={styles.messageLabel}>Latest customer activity · {fmtTime(selected.occurred_at)}</div>{selected.subject?<div className={styles.subject}>{selected.subject}</div>:null}<div className={styles.body}>{selected.preview||"No message preview available."}</div></div>
        <div className={styles.message}><div className={styles.messageLabel}>Internal Notes</div>{notes.length?<div style={{display:"grid",gap:8,marginTop:10}}>{notes.map(n=><div key={n.id} style={{border:"1px solid #e6eaee",borderRadius:9,padding:10,background:"#fafbfc"}}><div style={{fontWeight:800,fontSize:12}}>{n.author_name||"Epic team"} · {fmtTime(n.created_at)}</div><div style={{marginTop:5,whiteSpace:"pre-wrap",fontSize:13}}>{n.note_text}</div></div>)}</div>:null}<textarea className={styles.search} style={{minHeight:80,resize:"vertical",marginTop:10}} value={noteText} onChange={e=>setNoteText(e.target.value)} placeholder="Add an internal note…"/><div className={styles.actions} style={{marginTop:10}}><button className={styles.secondary} disabled={busy||!noteText.trim()} onClick={()=>void addNote()}>Add Note</button></div></div>
        <div className={styles.actions}><button className={styles.secondary} onClick={()=>setCustomer360Open(true)}>Open Customer 360</button>{selected.opportunity_id&&selected.opportunity_status!=="booked"&&!selected.claimed_by_name?<button className={styles.secondary} disabled={busy} onClick={()=>void activateLead()}>{busy?"Activating…":"Make Active Lead"}</button>:null}{selected.opportunity_id&&selected.opportunity_status==="open"&&selected.claimed_by_name?<span className={styles.pill}>Active Lead · {selected.claimed_by_name}</span>:null}<button className={styles.primary} disabled={busy||!selected.is_open} onClick={()=>void closeThread()}>{busy?"Closing…":selected.is_open?"Close":"Closed"}</button></div>{!selected.is_open&&selected.handled_at?<div className={styles.cleanNote}>Closed {fmtTime(selected.handled_at)} by {selected.handled_by_name||"Epic team"}.</div>:<div className={styles.cleanNote}>Closing removes this inbound item from the active inbox. Active leads remain in the Leads queue. Any new inbound call, text, email, or TripWorks draft brings this conversation back.</div>}
      </div>:<div className={styles.empty}><div><strong>Select a conversation</strong><div style={{marginTop:8}}>Customer context and the latest inbound activity will appear here.</div></div></div>}</section>
    </div>
    {selected?<Customer360Modal open={customer360Open} onClose={()=>setCustomer360Open(false)} opportunityId={selected.opportunity_id} reservationId={selected.reservation_id} reservationConfirmation={selected.reservation_confirmation} phone={selected.phone} email={selected.email}/>:null}
  </>;
}